# Custom docker image
# Original: https://github.com/readthedocs/readthedocs-docker-images/blob/master/Dockerfile
FROM readthedocs/build:latest
MAINTAINER Eduardo Blancas Reyes

RUN apt-get -y install tree